# values.yaml
image:
  repository: apinizeren/multi-env-app
  tag: "v0.0.2"
replicaCount: 2
service:
  nodePort: 30113
resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 500m, memory: 256Mi }
env:
  ENVIRONMENT: "prod"