image:
  repository: apinizeren/multi-env
  tag: ""               
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort        
  port: 8000            
  nodePort: null        

resources:
  requests: { cpu: 50m, memory: 64Mi }
  limits:   { cpu: 250m, memory: 128Mi }

probes:
  path: /health

env:
  ENVIRONMENT: ""