apiVersion: v1
kind: Secret
metadata:
  name: repo-oci-multi-env
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: multi-env-charts
  type: helm
  enableOCI: "true"
  url: registry-1.docker.io/apinizeren
  username: <REGISTRY_USER>
  password: <REGISTRY_TOKEN>